### ISSUE TITLE
No such file or directory, open "data.json"

### ISSUE THREAD

**Issue by mnemocron** [frankimhof/oqs-ssh-viz#1]
I am on Windows 10, WSL: Ubuntu 20.04.4 LTS on Windows 10 x86_64

The address: http://172.24.84.37:3000/ shows a fancy looking "404 not found". So I assume node.js works. but the data.json is missing.
Maybe because of the double slash in: `oqs-ssh-viz//build/data.json`

```bash
$ > pwd
/mnt/c/Users/simon/Downloads/FHNW/QSIT/oqs-ssh-viz
$ > npm --version
6.14.4
$ > nodejs --version
v10.19.0
$ > ./visualize.sh
Scanning the ../measurements folder
1) Exit
2) 2021-02-10_22-25-14_singapore
3) 2021-02-11_13-12-11_switzerland
4) 2021-02-12_18-35-28_hybrid-vs-pqonly
Which measurements do you want to visualize? 3
================================================================================
Reading data from CSV files...
[ '0_curve25519-sha256_ssh-ed25519.csv',
  '10_ecdh-nistp384-classic-mceliece-460896_p384-rainbowiiiccyclic.csv',
  '11_ecdh-nistp384-classic-mceliece-6688128_p384-rainbowiiiccycliccompressed.csv',
  '1_ecdh-nistp384-kyber-512_dilithium3.csv',
  '2_ecdh-nistp384-kyber-768_dilithium4.csv',
  '3_ecdh-nistp384-kyber-512-90s_p256-dilithium3.csv',
  '4_ecdh-nistp384-kyber-768-90s_p384-dilithium4.csv',
  '5_ecdh-nistp384-saber-lightsaber_falcon512.csv',
  '6_ecdh-nistp384-saber-saber_falcon1024.csv',
  '7_ecdh-nistp384-saber-saber_p256-falcon512.csv',
  '8_ecdh-nistp384-saber-firesaber_p521-falcon1024.csv',
  '9_ecdh-nistp384-classic-mceliece-460896f_p384-rainbowiiicclassic.csv' ]
================================================================================
Writing json data to data.json
(node:429) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/mnt/c/Users/simon/Downloads/FHNW/QSIT/oqs-ssh-viz//build/data.json'
(node:429) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:429) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npx: installed 90 in 11.596s
```

**Comment by mnemocron** [comment]
Aha! the `./build/` directory is missing. Maybe add an `mkdir build` to the visualize.sh ?

**Comment by mnemocron** [comment]
Also, two more things:

1. Are you sure port 5000 is correct?

```bash
$ > sudo lsof -i -P -n | grep LISTEN
node    132 simon   20u  IPv6  21525      0t0  TCP *:3000 (LISTEN)
```

2. the build folder only contains the json. Nothing else to host.

**Comment by frankimhof** [comment]
Ciao Simon

Bi grad unterwegs und ha mi laptop nid derbi.
Ich chas morn am morge aluege.

Hesch s Projekt chönne erfolgrich builde?
“npm run build” (vom projekt root folder us)
Wenn de command usgfüert hesch, sette html und js dateie im build ordner
zfinde si.

Wegem Port bini nüm ganz sicher, wenns nid 5000 isch, denn isches 3000.
Aber wie gseit, ich luegs morn nomol ah.

Lg
Frank

**Comment by frankimhof** [comment]
Hi

You first need to build the project:
Run `npm run build` (from the project root folder). Then try running `visualize.js` again.

**Comment by frankimhof** [comment]
> Aha! the `./build/` directory is missing. Maybe add an `mkdir build` to the visualize.sh ?

Thank you for your feedback.
The build directory is missing because you probably forgot to run `npm run build` first.

To improve this, I will add the command `npm run build` to the installation instruction steps in the README file.

**Comment by mnemocron** [comment]
Ok, yes. The way the README is organized currently it looks like you only need to do this if you want to develop stuff.
So maybe remove the "development" title.

And now I am farily sure I am getting WSL related errors and not to your project.


```bash
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /mnt/c/Users/simon/Downloads/FHNW/QSIT/oqs-ssh-viz/node_modules/webpack-dev-server
npm ERR! dest /mnt/c/Users/simon/Downloads/FHNW/QSIT/oqs-ssh-viz/node_modules/.webpack-dev-server.DELETE
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied
```
